/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Anniversary = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Int,
  'emoji' : IDL.Text,
});
export const CheckIn = IDL.Record({
  'emotion' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
});
export const GalaxyCounts = IDL.Record({
  'loveLetters' : IDL.Nat,
  'anniversaries' : IDL.Nat,
  'completedMissions' : IDL.Nat,
  'memories' : IDL.Nat,
});
export const LoveLetter = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'authorName' : IDL.Text,
});
export const MemoryVaultEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : IDL.Int,
  'photo' : IDL.Opt(ExternalBlob),
});
export const EmojiReaction = IDL.Record({
  'count' : IDL.Nat,
  'emoji' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'timestamp' : IDL.Int,
  'senderName' : IDL.Text,
  'reactions' : IDL.Vec(EmojiReaction),
  'voiceBlob' : IDL.Opt(ExternalBlob),
});
export const CoupleMission = IDL.Record({
  'id' : IDL.Nat,
  'completedAt' : IDL.Int,
  'title' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'xpReward' : IDL.Nat,
  'description' : IDL.Text,
});
export const PhotoOfDay = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Int,
  'createdAt' : IDL.Int,
  'caption' : IDL.Text,
  'photo' : ExternalBlob,
});
export const TimeCapsuleWithLockState = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'authorName' : IDL.Text,
  'unlockAt' : IDL.Int,
  'isUnlocked' : IDL.Bool,
});
export const CoupleChallenge = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'description' : IDL.Text,
  'weekStartTimestamp' : IDL.Int,
  'currentCount' : IDL.Nat,
  'targetCount' : IDL.Nat,
});
export const QuizAnswer = IDL.Record({
  'partnerName' : IDL.Text,
  'answer' : IDL.Text,
  'timestamp' : IDL.Int,
  'questionId' : IDL.Nat,
});
export const TimeCapsuleMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'authorName' : IDL.Text,
  'unlockAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addAnniversary' : IDL.Func([IDL.Text, IDL.Int, IDL.Text], [], []),
  'addCheckIn' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'addLoveLetter' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addMemory' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'addMission' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'addPhotoOfDay' : IDL.Func([IDL.Text, ExternalBlob, IDL.Int], [], []),
  'addReaction' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addTimeCapsuleMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [], []),
  'completeMission' : IDL.Func([IDL.Nat], [], []),
  'deleteLoveLetter' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteMemory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteMessage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePhotoOfDay' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllAnniversaries' : IDL.Func([], [IDL.Vec(Anniversary)], ['query']),
  'getAllCheckIns' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
  'getAllGalaxyItems' : IDL.Func([], [GalaxyCounts], ['query']),
  'getAllLoveLetters' : IDL.Func([], [IDL.Vec(LoveLetter)], ['query']),
  'getAllMemories' : IDL.Func([], [IDL.Vec(MemoryVaultEntry)], ['query']),
  'getAllMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getAllMissions' : IDL.Func([], [IDL.Vec(CoupleMission)], ['query']),
  'getAllPhotosOfDay' : IDL.Func([], [IDL.Vec(PhotoOfDay)], ['query']),
  'getAllTimeCapsuleMessages' : IDL.Func(
      [],
      [IDL.Vec(TimeCapsuleWithLockState)],
      ['query'],
    ),
  'getCoachTipSeed' : IDL.Func([], [IDL.Nat], ['query']),
  'getCompatibilityScore' : IDL.Func([], [IDL.Nat], ['query']),
  'getConversationStarterSeed' : IDL.Func([], [IDL.Nat], ['query']),
  'getCurrentWeekChallenges' : IDL.Func(
      [],
      [IDL.Vec(CoupleChallenge)],
      ['query'],
    ),
  'getDaysTogether' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
  'getMoodPrediction' : IDL.Func([], [IDL.Bool], ['query']),
  'getQuizAnswers' : IDL.Func([], [IDL.Vec(QuizAnswer)], ['query']),
  'getRelationshipLevel' : IDL.Func([], [IDL.Nat], ['query']),
  'getRelationshipXP' : IDL.Func([], [IDL.Nat], ['query']),
  'getSeasonalThemeEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'getSharedGoal' : IDL.Func([], [IDL.Text], ['query']),
  'getStartDate' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
  'getStreakCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTodaysPhoto' : IDL.Func([], [IDL.Opt(PhotoOfDay)], ['query']),
  'getTodaysPrompt' : IDL.Func([], [IDL.Text], ['query']),
  'getTotalXP' : IDL.Func([], [IDL.Nat], ['query']),
  'getUnlockedTimeCapsuleMessages' : IDL.Func(
      [],
      [IDL.Vec(TimeCapsuleMessage)],
      ['query'],
    ),
  'incrementChallengeProgress' : IDL.Func([IDL.Nat], [], []),
  'initWeeklyChallenges' : IDL.Func([], [], []),
  'removeAnniversary' : IDL.Func([IDL.Nat], [], []),
  'removeReaction' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'resetWeeklyChallenges' : IDL.Func([], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'sendVoiceNote' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'setCoachTipSeed' : IDL.Func([IDL.Nat], [], []),
  'setConversationStarterSeed' : IDL.Func([IDL.Nat], [], []),
  'setSeasonalThemeEnabled' : IDL.Func([IDL.Bool], [], []),
  'setSharedGoal' : IDL.Func([IDL.Text], [], []),
  'setStartDate' : IDL.Func([IDL.Int], [], []),
  'submitQuizAnswer' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateRelationshipLevel' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Anniversary = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Int,
    'emoji' : IDL.Text,
  });
  const CheckIn = IDL.Record({
    'emotion' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
  });
  const GalaxyCounts = IDL.Record({
    'loveLetters' : IDL.Nat,
    'anniversaries' : IDL.Nat,
    'completedMissions' : IDL.Nat,
    'memories' : IDL.Nat,
  });
  const LoveLetter = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'authorName' : IDL.Text,
  });
  const MemoryVaultEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : IDL.Int,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const EmojiReaction = IDL.Record({ 'count' : IDL.Nat, 'emoji' : IDL.Text });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'timestamp' : IDL.Int,
    'senderName' : IDL.Text,
    'reactions' : IDL.Vec(EmojiReaction),
    'voiceBlob' : IDL.Opt(ExternalBlob),
  });
  const CoupleMission = IDL.Record({
    'id' : IDL.Nat,
    'completedAt' : IDL.Int,
    'title' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'xpReward' : IDL.Nat,
    'description' : IDL.Text,
  });
  const PhotoOfDay = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Int,
    'createdAt' : IDL.Int,
    'caption' : IDL.Text,
    'photo' : ExternalBlob,
  });
  const TimeCapsuleWithLockState = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'authorName' : IDL.Text,
    'unlockAt' : IDL.Int,
    'isUnlocked' : IDL.Bool,
  });
  const CoupleChallenge = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'description' : IDL.Text,
    'weekStartTimestamp' : IDL.Int,
    'currentCount' : IDL.Nat,
    'targetCount' : IDL.Nat,
  });
  const QuizAnswer = IDL.Record({
    'partnerName' : IDL.Text,
    'answer' : IDL.Text,
    'timestamp' : IDL.Int,
    'questionId' : IDL.Nat,
  });
  const TimeCapsuleMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'authorName' : IDL.Text,
    'unlockAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addAnniversary' : IDL.Func([IDL.Text, IDL.Int, IDL.Text], [], []),
    'addCheckIn' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'addLoveLetter' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addMemory' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)], [], []),
    'addMission' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'addPhotoOfDay' : IDL.Func([IDL.Text, ExternalBlob, IDL.Int], [], []),
    'addReaction' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addTimeCapsuleMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [], []),
    'completeMission' : IDL.Func([IDL.Nat], [], []),
    'deleteLoveLetter' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteMemory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteMessage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePhotoOfDay' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllAnniversaries' : IDL.Func([], [IDL.Vec(Anniversary)], ['query']),
    'getAllCheckIns' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
    'getAllGalaxyItems' : IDL.Func([], [GalaxyCounts], ['query']),
    'getAllLoveLetters' : IDL.Func([], [IDL.Vec(LoveLetter)], ['query']),
    'getAllMemories' : IDL.Func([], [IDL.Vec(MemoryVaultEntry)], ['query']),
    'getAllMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getAllMissions' : IDL.Func([], [IDL.Vec(CoupleMission)], ['query']),
    'getAllPhotosOfDay' : IDL.Func([], [IDL.Vec(PhotoOfDay)], ['query']),
    'getAllTimeCapsuleMessages' : IDL.Func(
        [],
        [IDL.Vec(TimeCapsuleWithLockState)],
        ['query'],
      ),
    'getCoachTipSeed' : IDL.Func([], [IDL.Nat], ['query']),
    'getCompatibilityScore' : IDL.Func([], [IDL.Nat], ['query']),
    'getConversationStarterSeed' : IDL.Func([], [IDL.Nat], ['query']),
    'getCurrentWeekChallenges' : IDL.Func(
        [],
        [IDL.Vec(CoupleChallenge)],
        ['query'],
      ),
    'getDaysTogether' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
    'getMoodPrediction' : IDL.Func([], [IDL.Bool], ['query']),
    'getQuizAnswers' : IDL.Func([], [IDL.Vec(QuizAnswer)], ['query']),
    'getRelationshipLevel' : IDL.Func([], [IDL.Nat], ['query']),
    'getRelationshipXP' : IDL.Func([], [IDL.Nat], ['query']),
    'getSeasonalThemeEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'getSharedGoal' : IDL.Func([], [IDL.Text], ['query']),
    'getStartDate' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
    'getStreakCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTodaysPhoto' : IDL.Func([], [IDL.Opt(PhotoOfDay)], ['query']),
    'getTodaysPrompt' : IDL.Func([], [IDL.Text], ['query']),
    'getTotalXP' : IDL.Func([], [IDL.Nat], ['query']),
    'getUnlockedTimeCapsuleMessages' : IDL.Func(
        [],
        [IDL.Vec(TimeCapsuleMessage)],
        ['query'],
      ),
    'incrementChallengeProgress' : IDL.Func([IDL.Nat], [], []),
    'initWeeklyChallenges' : IDL.Func([], [], []),
    'removeAnniversary' : IDL.Func([IDL.Nat], [], []),
    'removeReaction' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'resetWeeklyChallenges' : IDL.Func([], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'sendVoiceNote' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'setCoachTipSeed' : IDL.Func([IDL.Nat], [], []),
    'setConversationStarterSeed' : IDL.Func([IDL.Nat], [], []),
    'setSeasonalThemeEnabled' : IDL.Func([IDL.Bool], [], []),
    'setSharedGoal' : IDL.Func([IDL.Text], [], []),
    'setStartDate' : IDL.Func([IDL.Int], [], []),
    'submitQuizAnswer' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateRelationshipLevel' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };