/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'timestamp' : bigint,
  'senderName' : string,
  'reactions' : Array<EmojiReaction>,
}
export interface CheckIn {
  'emotion' : string,
  'note' : [] | [string],
  'timestamp' : bigint,
}
export interface EmojiReaction { 'count' : bigint, 'emoji' : string }
export type ExternalBlob = Uint8Array;
export interface MemoryVaultEntry {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'timestamp' : bigint,
  'photo' : [] | [ExternalBlob],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addCheckIn' : ActorMethod<[string, [] | [string]], undefined>,
  'addMemory' : ActorMethod<[string, string, [] | [ExternalBlob]], undefined>,
  'addReaction' : ActorMethod<[bigint, string], undefined>,
  'getAllCheckIns' : ActorMethod<[], Array<CheckIn>>,
  'getAllMemories' : ActorMethod<[], Array<MemoryVaultEntry>>,
  'getAllMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getDaysTogether' : ActorMethod<[], [] | [bigint]>,
  'getStartDate' : ActorMethod<[], [] | [bigint]>,
  'getTodaysPrompt' : ActorMethod<[], string>,
  'removeReaction' : ActorMethod<[bigint, string], undefined>,
  'sendMessage' : ActorMethod<[string, string], undefined>,
  'setStartDate' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];