/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Anniversary {
  'id' : bigint,
  'title' : string,
  'date' : bigint,
  'emoji' : string,
}
export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'timestamp' : bigint,
  'senderName' : string,
  'reactions' : Array<EmojiReaction>,
  'voiceBlob' : [] | [ExternalBlob],
}
export interface CheckIn {
  'emotion' : string,
  'note' : [] | [string],
  'timestamp' : bigint,
}
export interface CoupleChallenge {
  'id' : bigint,
  'title' : string,
  'isCompleted' : boolean,
  'description' : string,
  'weekStartTimestamp' : bigint,
  'currentCount' : bigint,
  'targetCount' : bigint,
}
export interface CoupleMission {
  'id' : bigint,
  'completedAt' : bigint,
  'title' : string,
  'isCompleted' : boolean,
  'xpReward' : bigint,
  'description' : string,
}
export interface EmojiReaction { 'count' : bigint, 'emoji' : string }
export type ExternalBlob = Uint8Array;
export interface GalaxyCounts {
  'loveLetters' : bigint,
  'anniversaries' : bigint,
  'completedMissions' : bigint,
  'memories' : bigint,
}
export interface LoveLetter {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'authorName' : string,
}
export interface MemoryVaultEntry {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'timestamp' : bigint,
  'photo' : [] | [ExternalBlob],
}
export interface PhotoOfDay {
  'id' : bigint,
  'date' : bigint,
  'createdAt' : bigint,
  'caption' : string,
  'photo' : ExternalBlob,
}
export interface QuizAnswer {
  'partnerName' : string,
  'answer' : string,
  'timestamp' : bigint,
  'questionId' : bigint,
}
export interface TimeCapsuleMessage {
  'id' : bigint,
  'content' : string,
  'createdAt' : bigint,
  'authorName' : string,
  'unlockAt' : bigint,
}
export interface TimeCapsuleWithLockState {
  'id' : bigint,
  'content' : string,
  'createdAt' : bigint,
  'authorName' : string,
  'unlockAt' : bigint,
  'isUnlocked' : boolean,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addAnniversary' : ActorMethod<[string, bigint, string], undefined>,
  'addCheckIn' : ActorMethod<[string, [] | [string]], undefined>,
  'addLoveLetter' : ActorMethod<[string, string, string], undefined>,
  'addMemory' : ActorMethod<[string, string, [] | [ExternalBlob]], undefined>,
  'addMission' : ActorMethod<[string, string, bigint], undefined>,
  'addPhotoOfDay' : ActorMethod<[string, ExternalBlob, bigint], undefined>,
  'addReaction' : ActorMethod<[bigint, string], undefined>,
  'addTimeCapsuleMessage' : ActorMethod<[string, string, bigint], undefined>,
  'completeMission' : ActorMethod<[bigint], undefined>,
  'deleteLoveLetter' : ActorMethod<[bigint], boolean>,
  'deleteMemory' : ActorMethod<[bigint], boolean>,
  'deleteMessage' : ActorMethod<[bigint], boolean>,
  'deletePhotoOfDay' : ActorMethod<[bigint], boolean>,
  'getAllAnniversaries' : ActorMethod<[], Array<Anniversary>>,
  'getAllCheckIns' : ActorMethod<[], Array<CheckIn>>,
  'getAllGalaxyItems' : ActorMethod<[], GalaxyCounts>,
  'getAllLoveLetters' : ActorMethod<[], Array<LoveLetter>>,
  'getAllMemories' : ActorMethod<[], Array<MemoryVaultEntry>>,
  'getAllMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getAllMissions' : ActorMethod<[], Array<CoupleMission>>,
  'getAllPhotosOfDay' : ActorMethod<[], Array<PhotoOfDay>>,
  'getAllTimeCapsuleMessages' : ActorMethod<
    [],
    Array<TimeCapsuleWithLockState>
  >,
  'getCoachTipSeed' : ActorMethod<[], bigint>,
  'getCompatibilityScore' : ActorMethod<[], bigint>,
  'getConversationStarterSeed' : ActorMethod<[], bigint>,
  'getCurrentWeekChallenges' : ActorMethod<[], Array<CoupleChallenge>>,
  'getDaysTogether' : ActorMethod<[], [] | [bigint]>,
  'getMoodPrediction' : ActorMethod<[], boolean>,
  'getQuizAnswers' : ActorMethod<[], Array<QuizAnswer>>,
  'getRelationshipLevel' : ActorMethod<[], bigint>,
  'getRelationshipXP' : ActorMethod<[], bigint>,
  'getSeasonalThemeEnabled' : ActorMethod<[], boolean>,
  'getSharedGoal' : ActorMethod<[], string>,
  'getStartDate' : ActorMethod<[], [] | [bigint]>,
  'getStreakCount' : ActorMethod<[], bigint>,
  'getTodaysPhoto' : ActorMethod<[], [] | [PhotoOfDay]>,
  'getTodaysPrompt' : ActorMethod<[], string>,
  'getTotalXP' : ActorMethod<[], bigint>,
  'getUnlockedTimeCapsuleMessages' : ActorMethod<[], Array<TimeCapsuleMessage>>,
  'incrementChallengeProgress' : ActorMethod<[bigint], undefined>,
  'initWeeklyChallenges' : ActorMethod<[], undefined>,
  'removeAnniversary' : ActorMethod<[bigint], undefined>,
  'removeReaction' : ActorMethod<[bigint, string], undefined>,
  'resetWeeklyChallenges' : ActorMethod<[], undefined>,
  'sendMessage' : ActorMethod<[string, string], undefined>,
  'sendVoiceNote' : ActorMethod<[string, ExternalBlob], undefined>,
  'setCoachTipSeed' : ActorMethod<[bigint], undefined>,
  'setConversationStarterSeed' : ActorMethod<[bigint], undefined>,
  'setSeasonalThemeEnabled' : ActorMethod<[boolean], undefined>,
  'setSharedGoal' : ActorMethod<[string], undefined>,
  'setStartDate' : ActorMethod<[bigint], undefined>,
  'submitQuizAnswer' : ActorMethod<[bigint, string, string], undefined>,
  'updateRelationshipLevel' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];