/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CheckIn = IDL.Record({
  'emotion' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
});
export const MemoryVaultEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : IDL.Int,
  'photo' : IDL.Opt(ExternalBlob),
});
export const EmojiReaction = IDL.Record({
  'count' : IDL.Nat,
  'emoji' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'timestamp' : IDL.Int,
  'senderName' : IDL.Text,
  'reactions' : IDL.Vec(EmojiReaction),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addCheckIn' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'addMemory' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'addReaction' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getAllCheckIns' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
  'getAllMemories' : IDL.Func([], [IDL.Vec(MemoryVaultEntry)], ['query']),
  'getAllMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getDaysTogether' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
  'getStartDate' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
  'getTodaysPrompt' : IDL.Func([], [IDL.Text], ['query']),
  'removeReaction' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setStartDate' : IDL.Func([IDL.Int], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CheckIn = IDL.Record({
    'emotion' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
  });
  const MemoryVaultEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : IDL.Int,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const EmojiReaction = IDL.Record({ 'count' : IDL.Nat, 'emoji' : IDL.Text });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'timestamp' : IDL.Int,
    'senderName' : IDL.Text,
    'reactions' : IDL.Vec(EmojiReaction),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addCheckIn' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'addMemory' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)], [], []),
    'addReaction' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getAllCheckIns' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
    'getAllMemories' : IDL.Func([], [IDL.Vec(MemoryVaultEntry)], ['query']),
    'getAllMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getDaysTogether' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
    'getStartDate' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
    'getTodaysPrompt' : IDL.Func([], [IDL.Text], ['query']),
    'removeReaction' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setStartDate' : IDL.Func([IDL.Int], [], []),
  });
};

export const init = ({ IDL }) => { return []; };