/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Anniversary = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Int,
  'emoji' : IDL.Text,
});
export const CheckIn = IDL.Record({
  'emotion' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
});
export const MemoryVaultEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : IDL.Int,
  'photo' : IDL.Opt(ExternalBlob),
});
export const EmojiReaction = IDL.Record({
  'count' : IDL.Nat,
  'emoji' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'timestamp' : IDL.Int,
  'senderName' : IDL.Text,
  'reactions' : IDL.Vec(EmojiReaction),
});
export const CoupleMission = IDL.Record({
  'id' : IDL.Nat,
  'completedAt' : IDL.Int,
  'title' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'xpReward' : IDL.Nat,
  'description' : IDL.Text,
});
export const TimeCapsuleWithLockState = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'authorName' : IDL.Text,
  'unlockAt' : IDL.Int,
  'isUnlocked' : IDL.Bool,
});
export const QuizAnswer = IDL.Record({
  'partnerName' : IDL.Text,
  'answer' : IDL.Text,
  'timestamp' : IDL.Int,
  'questionId' : IDL.Nat,
});
export const TimeCapsuleMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'authorName' : IDL.Text,
  'unlockAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addAnniversary' : IDL.Func([IDL.Text, IDL.Int, IDL.Text], [], []),
  'addCheckIn' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'addMemory' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'addMission' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'addReaction' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addTimeCapsuleMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [], []),
  'completeMission' : IDL.Func([IDL.Nat], [], []),
  'getAllAnniversaries' : IDL.Func([], [IDL.Vec(Anniversary)], ['query']),
  'getAllCheckIns' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
  'getAllMemories' : IDL.Func([], [IDL.Vec(MemoryVaultEntry)], ['query']),
  'getAllMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getAllMissions' : IDL.Func([], [IDL.Vec(CoupleMission)], ['query']),
  'getAllTimeCapsuleMessages' : IDL.Func(
      [],
      [IDL.Vec(TimeCapsuleWithLockState)],
      ['query'],
    ),
  'getCompatibilityScore' : IDL.Func([], [IDL.Nat], ['query']),
  'getDaysTogether' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
  'getQuizAnswers' : IDL.Func([], [IDL.Vec(QuizAnswer)], ['query']),
  'getStartDate' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
  'getTodaysPrompt' : IDL.Func([], [IDL.Text], ['query']),
  'getTotalXP' : IDL.Func([], [IDL.Nat], ['query']),
  'getUnlockedTimeCapsuleMessages' : IDL.Func(
      [],
      [IDL.Vec(TimeCapsuleMessage)],
      ['query'],
    ),
  'removeAnniversary' : IDL.Func([IDL.Nat], [], []),
  'removeReaction' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setStartDate' : IDL.Func([IDL.Int], [], []),
  'submitQuizAnswer' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Anniversary = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Int,
    'emoji' : IDL.Text,
  });
  const CheckIn = IDL.Record({
    'emotion' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
  });
  const MemoryVaultEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : IDL.Int,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const EmojiReaction = IDL.Record({ 'count' : IDL.Nat, 'emoji' : IDL.Text });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'timestamp' : IDL.Int,
    'senderName' : IDL.Text,
    'reactions' : IDL.Vec(EmojiReaction),
  });
  const CoupleMission = IDL.Record({
    'id' : IDL.Nat,
    'completedAt' : IDL.Int,
    'title' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'xpReward' : IDL.Nat,
    'description' : IDL.Text,
  });
  const TimeCapsuleWithLockState = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'authorName' : IDL.Text,
    'unlockAt' : IDL.Int,
    'isUnlocked' : IDL.Bool,
  });
  const QuizAnswer = IDL.Record({
    'partnerName' : IDL.Text,
    'answer' : IDL.Text,
    'timestamp' : IDL.Int,
    'questionId' : IDL.Nat,
  });
  const TimeCapsuleMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'authorName' : IDL.Text,
    'unlockAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addAnniversary' : IDL.Func([IDL.Text, IDL.Int, IDL.Text], [], []),
    'addCheckIn' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'addMemory' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)], [], []),
    'addMission' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'addReaction' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addTimeCapsuleMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [], []),
    'completeMission' : IDL.Func([IDL.Nat], [], []),
    'getAllAnniversaries' : IDL.Func([], [IDL.Vec(Anniversary)], ['query']),
    'getAllCheckIns' : IDL.Func([], [IDL.Vec(CheckIn)], ['query']),
    'getAllMemories' : IDL.Func([], [IDL.Vec(MemoryVaultEntry)], ['query']),
    'getAllMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getAllMissions' : IDL.Func([], [IDL.Vec(CoupleMission)], ['query']),
    'getAllTimeCapsuleMessages' : IDL.Func(
        [],
        [IDL.Vec(TimeCapsuleWithLockState)],
        ['query'],
      ),
    'getCompatibilityScore' : IDL.Func([], [IDL.Nat], ['query']),
    'getDaysTogether' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
    'getQuizAnswers' : IDL.Func([], [IDL.Vec(QuizAnswer)], ['query']),
    'getStartDate' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
    'getTodaysPrompt' : IDL.Func([], [IDL.Text], ['query']),
    'getTotalXP' : IDL.Func([], [IDL.Nat], ['query']),
    'getUnlockedTimeCapsuleMessages' : IDL.Func(
        [],
        [IDL.Vec(TimeCapsuleMessage)],
        ['query'],
      ),
    'removeAnniversary' : IDL.Func([IDL.Nat], [], []),
    'removeReaction' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setStartDate' : IDL.Func([IDL.Int], [], []),
    'submitQuizAnswer' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };